# Generated by Django 3.0.8 on 2020-07-25 09:05
#このファイルはmakemigrationをするたび生成される。
# models.pyを元に作成された、より細かいtableの設計書。中間生成物。

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoModel',
            fields=[
                # データごとにidがデフォルトで自動でふられるようになっている。
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('memo', models.TextField()),
            ],
        ),
    ]
