# Generated by Django 3.0.8 on 2020-08-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200803_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='priority',
            field=models.CharField(choices=[('warning', 'high'), ('info', 'normal'), ('success', 'low')], max_length=50),
        ),
    ]
